export const FETCH_MOVIE_REQUEST = 'FETCH_MOVIE_REQUEST' 
export const FETCH_MOVIE_REQUEST_SUCCESS = 'FETCH_MOVIE_REQUEST_SUCCESS' 
export const FETCH_MOVIE_REQUEST_FAILURE = 'FETCH_MOVIE_REQUEST_FAILURE' 
export const SET_CURRENT_USER = 'SET_CURRENT_USER'