export const FETCH_MOVIE_REQUEST = 'FETCH_MOVIE_REQUEST' 
export const FETCH_MOVIE_REQUEST_SUCCESS = 'FETCH_MOVIE_REQUEST_SUCCESS' 
export const FETCH_MOVIE_REQUEST_FAILURE = 'FETCH_MOVIE_REQUEST_FAILURE' 
export const SET_CURRENT_USER = 'SET_CURRENT_USER'


export const ADD_MOVIE_REQUEST = 'ADD_MOVIE_REQUEST'
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS'
export const ADD_MOVIE_FAILURE = 'ADD_MOVIE_FAILURE'