'use strict'

export const GETBLOG = 'GETBLOG'
export const GET_VERIFICATION_CODE = 'GET_VERIFICATION_CODE'
export const SIGNUPREQUEST = 'SIGNUPREQUEST'
export const SIGNUPREQUESTSUCCESS = 'SIGNUPREQUESTSUCCESS'
export const SIGNUPREQUESTFAILURE = 'SIGNUPREQUESTFAILURE'